### ISSUE TITLE
Create  Models for Elective Subject Choices

### ISSUE THREAD

**Issue by boniface** [boniface/uniframework#2]
Could you tell your team that we need to focus on the aspect of the application that will allow students to select Electives as a first case that will use the uniframework.  Create a domain model of all the items that will be needed to manage the selection of the electives. Key things are 

-Elective  descriptions
-Time Electives are offered
-The quota for the electives 
-The status for the electives when full
-A place to see the study guides for the electives
-The Lecturers teaching the electives
-In the background, there should be a mechanism to email the respective lecturers the number of students that have subscribed to their course

**Comment by boniface** [comment]
We probably would need to divide this into tasks and assign them to group members

**Comment by Koumou** [comment]
For that Model, Can we use the following classes:

- Lecture (subclass of staff)
- Stream (associative  of course and subject)
- Elective (subclass of subject)
- Elective controller.

**Comment by Koumou** [comment]
not resolved
